CREATE TABLE CUSTOMER (
    customer_id VARCHAR2(20) CONSTRAINT PK_CUSTOMER PRIMARY KEY,
    customer_name VARCHAR2(20) CONSTRAINT NT_CUSTOMER NOT NULL,
    customer_tel NUMBER
);

CREATE TABLE PRODUCT (
    product_id VARCHAR2(20) CONSTRAINT PK_PRODUCT PRIMARY KEY,
    product_name VARCHAR2(20) CONSTRAINT NT_PRODUCT NOT NULL,
    price NUMBER CONSTRAINT POSITIVE CHECK (price>0)
);
CREATE TABLE ORDERS (
    product_id VARCHAR2(20),
    customer_id VARCHAR2(20),
    quantity NUMBER,
    total_amount NUMBER,
    CONSTRAINT FK_ORDER1 FOREIGN KEY (product_id) REFERENCES PRODUCT (product_id),
    CONSTRAINT FK_ORDER2 FOREIGN KEY (customer_id) REFERENCES CUSTOMER (customer_id)
);
ALTER TABLE PRODUCT ADD Category VARCHAR2(20);
ALTER TABLE ORDERS MODIFY  OrderDate DATE DEFAULT  SYSDATE;

